version: '3.8'
services:
  hallyuhub:
    image: ghcr.io/uchidate/khub:latest
    container_name: hallyuhub
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/data/prod.db
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - hallyuhub-data:/app/data
    networks:
      - web

networks:
  web:
    external: true

volumes:
  hallyuhub-data:
