version: '3.8'

services:
  hallyuhub-prod:
    image: ghcr.io/uchidate/khub:latest
    container_name: hallyuhub
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - hallyuhub-data:/app/data
    networks:
      - web
    restart: always

networks:
  web:
    external: true

volumes:
  hallyuhub-data:
    external: true
