services:
  db:
    image: postgres:15-alpine
    container_name: hallyuhub_db_staging
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-hallyuhub_staging}
    ports:
      - "5433:5432"
    volumes:
      - staging_db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hallyuhub_web_staging
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-hallyuhub_staging}?schema=public
      NEXT_PUBLIC_SITE_URL: staging.seu-dominio.com
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: hallyuhub_nginx_staging
    restart: always
    ports:
      - "3001:80"
    volumes:
      - ./docker/nginx/nginx.staging.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  staging_db_data:
